stages:
  requires:
    cmd: pip install -r requirements.txt
    deps:
    - requirements.txt
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - train_features.csv
    - train_labels.csv
    - test_features.csv
    - test_labels.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    outs:
    - plot.png
    metrics:
    - metrics.txt:
        cache: false